### PR TITLE
fix issues with duplicate names

### LINKED ISSUE #47: sesame2spiner should handle material names
There should be a way to handle sesame files with missing or duplicate material names. Issue found by @dholladay00

### PR DESCRIPTION
**Pull request by Yurlungur**
## PR Checklist

In issue #47 @dholladay00 discovered that if two materials in a sesame2spiner file have the same "name" metadata, HDF5 throws an error. This PR adds guard rails so this can't happen, and also adds guard rails against a similar error when duplicate matids are requested.

Strategy uses a simple `std::unordered_list` to see what has been used already.

Resolves #47

- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.

### CODE REVIEW

**Comment by dholladay00** [comment]
@Yurlungur did you test sesame2spiner and verify that it avoids the issues.

**Comment by Yurlungur** [comment]
> @Yurlungur did you test sesame2spiner and verify that it avoids the issues. 

Yes. I added a new set of test inputs in the example directory, which gets run by the CI. These inputs have duplicate names and matids.

That said, it would be good to try it on your problem.

**Comment by dholladay00** [comment]
> > @Yurlungur did you test sesame2spiner and verify that it avoids the issues.
> 
> Yes. I added a new set of test inputs in the example directory, which gets run by the CI. These inputs have duplicate names and matids.
> 
> That said, it would be good to try it on your problem.

These changes fixed the issue I was seeing.

**Comment by Yurlungur** [comment]
> > > @Yurlungur did you test sesame2spiner and verify that it avoids the issues.
> > 
> > Yes. I added a new set of test inputs in the example directory, which gets run by the CI. These inputs have duplicate names and matids.
> > 
> > That said, it would be good to try it on your problem.
> 
> These changes fixed the issue I was seeing. 

Can you review/approve then?

File: sesame2spiner/generate_files.cpp [hunk 1]
```diff
@@ -171,12 +174,27 @@ herr_t saveAllMaterials(const std::string &savename,
...
     eosGetMetadata(matid, metadata, Verbosity::Debug);
     if (printMetadata) std::cout << metadata << std::endl;
     std::string name = params[i].Get("name", metadata.name);
+    if (used_names.count(name) > 0) {
+      std::string new_name = "material_" + std::to_string(i);
+      std::cerr << "...WARNING: Name " << name << " already used. "
+		<< "using a default name: "
+		<< new_name
+		<< std::endl;
+      name = new_name;
```
Comment (dholladay00) [inline sesame2spiner/generate_files.cpp:195]: what about using the repeated name + an integer @Yurlungur ?

Comment (dholladay00) [reply sesame2spiner/generate_files.cpp:195]: @Yurlungur I'll approve once we resolve how to move forward on this.

Comment (Yurlungur) [reply sesame2spiner/generate_files.cpp:195]: Yeah, name + integer is fine. I did it this way because it's easier than tracking an integer count, but integer count should be easy too. Been under the weather a few days. Will do this when I'm at my desk again.

Comment (dholladay00) [reply sesame2spiner/generate_files.cpp:195]: maybe we use a default name if the "reused name" is an empty string, but if there is an actual name that is re-used, preserving some of that information could be useful to downstream users.

Comment (Yurlungur) [reply sesame2spiner/generate_files.cpp:195]: I'm not sure I can catch all the possible "empty string" names but I'll try.

Comment (Yurlungur) [reply sesame2spiner/generate_files.cpp:206]: @dholladay00 the new version does the following:
- If the name is an empty string or the string "-1", which I noticed some unnamed materials have in their name field, rename the material "material_n" where n is the number of the input deck passed into sesame2spiner
- If matids are repeated, skips the duplicate matid
- If two materials have the same, non-trivial name, `sesame2spiner` will enumerate them. i.e., if you had three materials named "metal," then in the sp5 file they'll be called `metal`, `metal_2`, `metal_3`.

Give it a try.

Comment (dholladay00) [reply sesame2spiner/generate_files.cpp:206]: This works great now!

**Review by dholladay00 — APPROVED** [review]
